##===----------------------------------------------------------------------===##
##
## This source file is part of the SwiftNIO open source project
##
## Copyright (c) 2025 Apple Inc. and the SwiftNIO project authors
## Licensed under Apache License v2.0
##
## See LICENSE.txt for license information
## See CONTRIBUTORS.txt for the list of SwiftNIO project authors
##
## SPDX-License-Identifier: Apache-2.0
##
##===----------------------------------------------------------------------===##

add_subdirectory(_NIOBase64)
add_subdirectory(_NIOConcurrency)
add_subdirectory(_NIODataStructures)
add_subdirectory(CNIOAtomics)
add_subdirectory(CNIODarwin)
add_subdirectory(CNIOLinux)
add_subdirectory(CNIOLLHTTP)
add_subdirectory(CNIOSHA1)
add_subdirectory(CNIOWASI)
add_subdirectory(CNIOWindows)
add_subdirectory(NIO)
add_subdirectory(NIOConcurrencyHelpers)
add_subdirectory(NIOCore)
add_subdirectory(NIOEmbedded)
add_subdirectory(NIOFoundationCompat)
add_subdirectory(NIOHTTP1)
add_subdirectory(NIOPosix)
add_subdirectory(NIOTestUtils)
add_subdirectory(NIOTLS)
add_subdirectory(NIOWebSocket)
